echo off
SET SSSDK=%~dp0
SET SSSDK=%SSSDK:~0,-1%
set SSSDK=%SSSDK:\=/%
SET PATH=%SSSDK%\SN;%SSSDK%\TOOLS;%PATH%
SET PATH=%SSSDK%\TOOLS\BGCON;%PATH%
SET PATH=%SSSDK%\TOOLS\SSSSDK;%PATH%
SET PATH=%SSSDK%\TOOLS\CommsL~1;%PATH%
SET PATH=%SSSDK%\TOOLS\CommsL~1\arplus;%PATH%
SET PATH=%SSSDK%\SH_COFF\sh-coff\bin;%PATH%
SET PATH=%SSSDK%\SH_COFF\sh-coff\sh-coff\bin;%PATH%
SET PATH=%SSSDK%\SH_COFF\OtherU~1;%PATH%
SET PATH=%SSSDK%\SGL_302j\TOOL;%PATH%
SET PATH=%SSSDK%\AWK;%PATH%
SET PATH=%SSSDK%\SBL_601\SEGABIN\BIN;%PATH%
SET PATH=%SSSDK%\SBL_601\SEGABIN\BINCD;%PATH%
SET PATH=%SSSDK%\E2\Toolkit;%PATH%

SET INFOPATH=%SSSDK%\SH_COFF\sh-coff\INFO;%INFOPATH%

SET C_INCLUDE_PATH=%SSSDK%\SH_COFF\sh-coff\sh-coff\include;%C_INCLUDE_PATH%
SET C_INCLUDE_PATH=%SSSDK%\RB\INC;%C_INCLUDE_PATH%
SET C_INCLUDE_PATH=%SSSDK%\SGL_302j\INC;%C_INCLUDE_PATH%
SET C_INCLUDE_PATH=%SSSDK%\SBL_601\SEGALIB\INCLUDE;%C_INCLUDE_PATH%
SET C_INCLUDE_PATH=%SSSDK%\DUCK\SATURN\SEGALIB\INCLUDE;%C_INCLUDE_PATH%
SET C_INCLUDE_PATH=%SSSDK%\TOOLS\BGCON;%C_INCLUDE_PATH%
SET C_INCLUDE_PATH=%SSSDK%\E2\Toolkit;%C_INCLUDE_PATH%
SET C_INCLUDE_PATH=%SSSDK%\DUCK\SATURN\SEGALIB\INCLUDE;%C_INCLUDE_PATH%


SET CPLUS_INCLUDE_PATH=%SSSDK%\SH_COFF\sh-coff\include\C__~1\36FAE~1.4-G;%CPLUS_INCLUDE_PATH%
SET CPLUS_INCLUDE_PATH=%SSSDK%\RB\INC;%CPLUS_INCLUDE_PATH%
SET CPLUS_INCLUDE_PATH=%SSSDK%\SGL_302j\INC;%CPLUS_INCLUDE_PATH%
SET CPLUS_INCLUDE_PATH=%SSSDK%\SBL_601\SEGALIB\INCLUDE;%CPLUS_INCLUDE_PATH%
SET CPLUS_INCLUDE_PATH=%SSSDK%\DUCK\SATURN\SEGALIB\INCLUDE;%CPLUS_INCLUDE_PATH%
SET CPLUS_INCLUDE_PATH=%SSSDK%\TOOLS\BGCON;%CPLUS_INCLUDE_PATH%
SET CPLUS_INCLUDE_PATH=%SSSDK%\E2\Toolkit;%CPLUS_INCLUDE_PATH%
SET CPLUS_INCLUDE_PATH=%SSSDK%\DUCK\SATURN\SEGALIB\INCLUDE;%CPLUS_INCLUDE_PATH%

REM AWK directories must be in DOS notation
SET AWKTMP=%SSSDK%\AWK\TMP
SET AWKENV=%SSSDK%\AWK
SET MAKE_MODE=unix
echo sssdk paths set
