PROJECT=europa
OBJFMT=coff
OUTPUTDIR=build

# source_program
 src/entry.c src/scl_data.c src/scl_func.c src/spr_data.c

# SYSOBJS = $(SGLLDR)/sglarea.o
OBJS = $(SRCS.c=.o)
# LIBS = -lsgl

include $(SSSDK)/COMMON/mf_SBL



